
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 25 19:44:55 BRT 2018
//----------------------------------------------------

package br.com.minic.analisadorsintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 32;
  public static final int CHAR = 5;
  public static final int SOMA = 29;
  public static final int ABRE_CHAVE = 34;
  public static final int LITERAL_PONTO_FLUTUANTE = 19;
  public static final int DIFERENTE = 28;
  public static final int FECHA_CHAVE = 35;
  public static final int DOUBLE = 7;
  public static final int LETRA_H = 41;
  public static final int INT = 4;
  public static final int NEGACAO = 42;
  public static final int PONTO = 39;
  public static final int VIRGULA = 33;
  public static final int IDENTIFICADOR = 17;
  public static final int IGUAL = 27;
  public static final int PRINTSTR = 14;
  public static final int DIV = 31;
  public static final int MAIN = 8;
  public static final int IF = 10;
  public static final int ID = 3;
  public static final int PRINTINT = 13;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int PONTO_VIRGULA = 40;
  public static final int ABRE_PARENTESES = 36;
  public static final int MAIOR = 24;
  public static final int error = 1;
  public static final int INCLUDE = 2;
  public static final int LITERAL_CHAR = 20;
  public static final int MENOR = 22;
  public static final int VOID = 16;
  public static final int LITERAL_INTEIRO = 18;
  public static final int JOGO_DA_VELHA = 38;
  public static final int PRINTF = 12;
  public static final int ELSE = 15;
  public static final int LITERAL_STRING = 21;
  public static final int WHILE = 11;
  public static final int FECHA_PARENTESES = 37;
  public static final int FLOAT = 6;
  public static final int ATRIBUICAO = 26;
  public static final int MENOR_IGUAL = 23;
  public static final int SUB = 30;
  public static final int MAIOR_IGUAL = 25;
}

